### ISSUE TITLE
error running on Ventura

### ISSUE THREAD

**Issue by hmarinox** [ChenghaoMou/touchbar-lyric#24]
❯ /opt/homebrew/bin/python3 -m touchbar_lyric --app music
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/opt/homebrew/lib/python3.10/site-packages/touchbar_lyric/__main__.py", line 57, in <module>
    typer.run(run)
  File "/opt/homebrew/lib/python3.10/site-packages/typer/main.py", line 859, in run
    app()
  File "/opt/homebrew/lib/python3.10/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/homebrew/lib/python3.10/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/homebrew/lib/python3.10/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/typer/main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "/opt/homebrew/lib/python3.10/site-packages/touchbar_lyric/__main__.py", line 44, in run
    songs = universal_search(media_info.name, media_info.artists)
  File "/opt/homebrew/lib/python3.10/site-packages/diskcache/core.py", line 1877, in wrapper
    result = func(*args, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/touchbar_lyric/service/__init__.py", line 45, in universal_search
    for i, s in enumerate(rentanadviser_music_search(title, artists)))
  File "/opt/homebrew/lib/python3.10/site-packages/touchbar_lyric/service/misc.py", line 55, in rentanadviser_music_search
    result_links = soup.find(id="tablecontainer").find_all("a")
AttributeError: 'NoneType' object has no attribute 'find_all'

**Comment by ChenghaoMou** [comment]
Thank you for reporting this!

The bug should be fixed in `0.8.1` and you can upgrade to the new version by running this command in your Terminal:

```
pip install touchbar_lyric --upgrade
```
